#!/usr/bin/env bash
# script that will display information about subdomains
# script accepts 2 arguments( domain and Subdomain)
# If only 1 argument is given it diplays information for its subdomains
# dig is used to look up the DNS information of the specific doman
# awk is used to extract specific information from the results of the dig command


if [ "$#" -eq 1 ]; then
    echo "$(dig www.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain www is a "$4" record and points to "$5}')"
    echo "$(dig lb-01.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain lb-01 is a "$4" record and points to "$5}')"
    echo "$(dig web-01.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-01 is a "$4" record and points to "$5}')"
    echo "$(dig web-02.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-02 is a "$4" record and points to "$5}')"
elif [ "$#" -eq 2 ]; then
    subdomain=$2
    echo "$(dig $subdomain.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain '"$subdomain"' is a "$4" record and points to "$5}')"
fi
