#!/usr/bin/env bash
# Bash script that install nginx on web-01 server

# update packages
sudo apt-get update

# install nginx
sudo apt-get -y install nginx

# configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# set landing page
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
