#!/usr/bin/env bash
# Configuring  Nginx server to /redirect_me to another page.
# The redirection is  "301 Moved Permanently"

#update packages
sudo apt-get -y update

#install nginx
sudo apt-get install -y nginx

# set landing page
echo "Hello World!" | sudo tee /var/www/html/index.html

#The 301 Moved Permanently redirection
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
