#!/usr/bin/env bash
# Configuring  Nginx server to /redirect_me to another page.
# The redirection is  "301 Moved Permanently"

#update packages
sudo apt-get -y update

#install nginx
sudo apt-get -y install nginx

# configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# set landing page
echo "Hello World!" | sudo tee /var/www/html/index.html

#The 301 Moved Permanently redirection
config="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/shorts/VAWGCzD4jtk;"
sudo sed -i "s/server_name _;/$config/" /etc/nginx/sites-enabled/default

sudo service nginx restart
