#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string "Ceci n'est pas une page"

# Update packages
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Set the landing page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure a 301 Moved Permanently redirection
sudo sed -i "/19i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default

# Create a 404 Custom error page if it doesn't exist
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

# Test the Nginx configuration for errors
sudo nginx -t

# Restart the web server (nginx) after changes
sudo service nginx restart
