#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string "Ceci n'est pas une page"

# Update packages
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Set the landing page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure a 301 Moved Permanently redirection
config="server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/shorts/VAWGCzD4jtk permanent;"
sudo sed -i "s|server_name _;|$config|" /etc/nginx/sites-enabled/default

# Create a 404 Custom error page if it doesn't exist
if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-enabled/default; then
    echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
    config="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
    sudo sed -i "/server_name _/a $config" /etc/nginx/sites-enabled/default
fi

# Test the Nginx configuration for errors
sudo nginx -t

# Restart the web server (nginx) after changes
sudo service nginx restart
