#!/usr/bin/env bash
# script that configures a new Ubuntu machine(sever) by installing
# a webserver(nginx) on it
# Http custom response header is added since there there will be a load
# balancer.This will be used to track which web server is answering our
# Http requests.

# update packages
sudo apt-get update

# install nginx
sudo apt-get install -y nginx

# seting landing page
echo "Hello World!" | sudo tee /var/www/html/index.html

# moved 301 Moved permanentely redirection
sudo sed -i "/19i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default
# create the custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# testing config for errors
sudo nginx -t

# restart webserver(nginx) after changes
sudo service nginx restart
