#!/usr/bin/env bash
# script that configures a new Ubuntu machine(sever) by installing
# a webserver(nginx) on it
# Http custom response header is added since there there will be a load
# balancer.This will be used to track which web server is answering our
# Http requests.

# update packages
sudo apt-get update

# install nginx
sudo apt-get install -y nginx

# seting landing page
echo "Hello World!" | sudo tee /var/www/html/index.html

# moved 301 Moved permanentely redirection
config="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/shorts/VAWGCzD4jtk;"
sudo sed -i "s/server_name _;/$config/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-enabled/default; then
        echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
        config="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
        sudo sed -i "s/listen 80 default_server;/$config/" /etc/nginx/sites-enabled/default
fi

# create the custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# testing config for errors
sudo nginx -t

# restart webserver(nginx) after changes
sudo service nginx restart
