#!/usr/bin/env bash
# Debug nginx web server to listen to port 80 and display nginx is not running when service status is checked
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
