#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed
# Script to manage my_process
#!/usr/bin/env bash
# Script to manage my_process

pid_file="/var/run/my_process.pid"

start_process() {
  bash ./manage_my_process &
  echo "$!" > "$pid_file"
  echo "my_process started"
}

stop_process() {
  if [ -e "$pid_file" ]; then
    pkill -F "$pid_file" && rm "$pid_file"
    echo "my_process stopped"
  else
    echo "my_process is not running"
  fi
}

restart_process() {
  stop_process
  start_process
  echo "my_process restarted"
}

command="$1"

case "$command" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
