#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed
pid_file="/var/run/my_process.pid"

start_process() {
  ./manage_my_process &
  echo "$!" > "$pid_file"
  echo "manage_my_process started"
}

stop_process() {
  if [ -f "$pid_file" ]; then
    echo "manage_my_process stopped"
    kill "$(cat "$pid_file")"
    rm "$pid_file"
  else
    echo "manage_my_process is not running"
  fi
}

restart_process() {
  echo "manage_my_process restarted"
}

case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac


