#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process.
# retrieve the PID of the 4-to_infinity_and_beyond process.
PID_of_4=$(pgrep -f 4-to_infinity_and_beyond)
kill "$PID_of_4"
