#!/usr/bin/env bash
# Write a manage_my_process Bash script
# Indefinitely writes "I am alive" to the file /tmp/my_process.
# In between every I am alive! message, the program should pause for 2 seconds
my_file="/tmp/my_process":
while true 
do
	echo "I am alive!" >> "$my_file"
	sleep 2
done
