#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
name="Best School"
counter=0
while [ $counter -le 9 ]
do
 	echo "$name"
	if [ $counter -eq 8 ]
	then
		echo "Hi"
	fi
 
	((counter++))
done

