#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and display bad luck on 4th iteration , good luck on 8th iteration and dispaly Best School for the rest
name="Best School"
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8  ]
	then
		echo "good luck"
	else
		echo "$name"
	fi
	((counter++))
done
