#!/usr/bin/env bash
# Displays numbers from 1-20,display 4 & bad luck from china on the 4th iteration
# Display 9 and bad luck from japan on 9th iteration
#  Display 17 and bad luck from Italy on 17th iteration
counter=1
while [ $counter -le 20 ]
do
	echo "$counter"
	case $counter in 
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		esac
		((counter++)) 
done
