#!/usr/bin/env bash
# onfigures an Ubuntu server with the follow requirement
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.


cp /etc/hosts ~/hosts.new
sed -i "/localdomain/a\8.8.8.8\tfacebook.com/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
